#!/bin/sh

# ------------------------------------------------------------------------------
# PRIVATE SHELL ALIASES
# ------------------------------------------------------------------------------
#
# Private shell aliases should be here.
# These include specific aliases that should not be shared across machines.

alias foo='echo foo'
